apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-agent-deployment
  labels:
    app: insurance-agent-pod
spec:
  replicas: 1
  strategy: # <-- This is the added block
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: insurance-agent-pod
  template:
    metadata:
      labels:
        app: insurance-agent-pod
    spec:
      containers:
      - name: insurance-agent
        image: emarhnuel/insurance-ai-agent:v3 
        ports:
        - containerPort: 8000
        startupProbe:
          httpGet:
            path: /docs
            port: 8000
          failureThreshold: 60
          periodSeconds: 10
          initialDelaySeconds: 0
        livenessProbe:
          httpGet:
            path: /docs
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /docs
            port: 8000
          initialDelaySeconds: 120
          periodSeconds: 15
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-secret
              key: OPENAI_API_KEY
        - name: OPENROUTER_API_KEY
          valueFrom:
            secretKeyRef:
              name: openrouter-secret
              key: OPENROUTER_API_KEY
        - name: MEM0_API_KEY
          valueFrom:
            secretKeyRef:
              name: mem0-secret
              key: MEM0_API_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: insurance-agent-service
spec:
  selector:
    app: insurance-agent-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer