apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
resources:
  - deploy.yaml

images:
  - name: emarhnuel/insurance-ai-agent:v2
    newName: gcr.io/PROJECT_ID/insurance-ai-agent
    newTag: GITHUB_SHA