apiVersion: v1
kind: Service
metadata:
  name: insurance-agent-service
spec:
  selector:
    app: insurance-agent-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30998
  type: LoadBalancer