name: Build and Deploy to GKE (Google Cloud Integrated)

on:
  push:
    branches:
      - main

env:
  # --- IMPORTANT: CONFIGURE YOUR ENVIRONMENT --- #
  # TODO: Replace 'your-gcp-project-id' with your actual GCP Project ID.
  GCP_PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  # TODO: Replace with your GKE cluster name and zone.
  GKE_CLUSTER: my-cluster
  GKE_ZONE: us-east1-c
  # The name of your application's deployment in Kubernetes.
  DEPLOYMENT_NAME: insurance-agent-deployment
  # The name for your Docker image in GCR.
  IMAGE_NAME: insurance-ai-agent

jobs:
  build-and-deploy:
    name: Build and Deploy to GKE
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # --- Authenticate with Google Cloud --- #
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          # This uses the GCP_SA_KEY secret you created in GitHub secrets.
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # --- Configure Docker for GCR --- #
      # This step configures Docker to use gcloud for authentication, so no
      # Docker Hub credentials are needed.
      - name: Configure Docker for GCR
        run: gcloud auth configure-docker --quiet

      # --- Build and Push Image to GCR --- #
      - name: Build and Push Docker Image
        run: |
          docker build \
            --tag "gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ github.sha }}" \
            --build-arg GITHUB_SHA="${{ github.sha }}" \
            .
          docker push "gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"

      # --- Deploy to GKE using Kustomize --- #
      - name: Get GKE Credentials
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}

      - name: Set Kustomize Image Tag
        run: |
          cd k8s/base
          kustomize edit set image gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE_NAME }}=gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          echo "Kustomize image tag set to: ${{ github.sha }}"

      - name: Deploy to GKE
        run: |
          echo "Applying Kustomize manifests..."
          kubectl apply -k k8s/base
          echo "Waiting for deployment rollout to complete..."
          kubectl rollout status deployment/${{ env.DEPLOYMENT_NAME }}
          echo "Deployment complete!"